name: Run Pixiv Downloader

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # This prevents GitHub token from being persisted

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pixivpy3

    - name: Run script
      run: python pixiv.py

    - name: Configure Git
      run: |
        git config --global user.name 'eifal'
        git config --global user.email 'syahrifal7@gmail.com'

    - name: Commit files
      run: |
        git add pix
        git commit -m "Add downloaded images" || echo "No changes to commit"

    - name: Push changes
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
        git push origin main
